version: "3.7"
services:
  web-app:
    container_name: "debug-client"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "4001:4001"
    networks:
      default:
        ipv4_address:  172.18.0.12
    restart: always

networks:
  default:
    external:
      name: docker-network