version: "3.3"
services:
  web-app:
    container_name: "debug_client"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4030:4030"
    networks:
      default:
        ipv4_address:  172.18.0.10
    restart: always

networks:
  default:
    external:
      name: docker-network
